name: list_counter
description: A utility for counting in a variety of languages and styles. Made for lists.
version: 1.0.2
homepage: https://github.com/Sub6Resources/ordered_list

environment:
  sdk: '>=2.18.1 <3.0.0'

dev_dependencies:
  test: ^1.21.6

